### ISSUE TITLE
sidesail: bad error on failing parent chain deposit

### ISSUE THREAD

**Issue by torkelrogstad** [LayerTwo-Labs/sidesail#200]
I think this is because I don't have enough funds on the mainchain. Would be nice with a better error message!

<img width="664" alt="image" src="https://github.com/user-attachments/assets/37c56901-58fb-415e-9aff-e8461098debe">

**Comment by octobocto** [comment]
This is not a sidesail issue, but a geth issue. false is the only thing geth returns.. we could assume that's the reason though, and hint the user to check it. Fixed in the next PR
