### ISSUE TITLE
Zside startup issues

### ISSUE THREAD

**Issue by torkelrogstad** [LayerTwo-Labs/sidesail#95]
Unable to start the Zside daemon that's bundled with Zsail. Perhaps this is best to fix through the launcher, or could we perhaps tweak the startup params?

<img width="1840" alt="image" src="https://github.com/barebitcoin/sidesail/assets/16610775/531ad273-3514-4df7-8eee-0c0179d348ab">

**Comment by octobocto** [comment]
Fixed with adding -walletrequirebackup=false to the default conf file #151
